#ifndef _INC_SWI_NUM_STUBS_MEM
#define _INC_SWI_NUM_STUBS_MEM

#define SWI_NUM_AddHead			        0
#define SWI_NUM_AddTail			        0
#define SWI_NUM_AllocMem			    0
#define SWI_NUM_AllocMemFromMemList		0
#define SWI_NUM_AllocMemFromMemLists	0
#define SWI_NUM_AllocMemList			0
#define SWI_NUM_AvailMem			    0
#define SWI_NUM_CallFolio			    0
#define SWI_NUM_CallFolioRet			0
#define SWI_NUM_CheckIO			        0
#define SWI_NUM_CheckItem			    0
#define SWI_NUM_ClearCurrentSignals		0
#define SWI_NUM_CloseNamedDevice		0
#define SWI_NUM_CountBits			    0
#define SWI_NUM_CreateBufferedMsg		0
#define SWI_NUM_CreateIOReq			    0
#define SWI_NUM_CreateItem			    0
#define SWI_NUM_CreateItemVA			0
#define SWI_NUM_CreateMemDebug			0
#define SWI_NUM_CreateMsg			    0
#define SWI_NUM_CreateMsgPort			0
#define SWI_NUM_CreateSemaphore			0
#define SWI_NUM_CreateSmallMsg			0
#define SWI_NUM_CreateThread			0
#define SWI_NUM_CreateUniqueMsgPort		0
#define SWI_NUM_CreateUniqueSemaphore	0
#define SWI_NUM_DeleteIOReq			    0
#define SWI_NUM_DeleteMemDebug			0
#define SWI_NUM_DeleteMsg			    0
#define SWI_NUM_DeleteMsgPort			0
#define SWI_NUM_DeleteSemaphore			0
#define SWI_NUM_DeleteThread			0
#define SWI_NUM_DumpMemDebug			0
#define SWI_NUM_DumpNode			    0
#define SWI_NUM_DumpTagList			    0
#define SWI_NUM_ffs			            0
#define SWI_NUM_FindAndOpenDevice		0
#define SWI_NUM_FindAndOpenFolio		0
#define SWI_NUM_FindAndOpenNamedItem	0
#define SWI_NUM_FindAndOpenItemVA		0
#define SWI_NUM_FindDevice			    0
#define SWI_NUM_FindFolio			    0
#define SWI_NUM_FindItemVA			    0
#define SWI_NUM_FindLSB			        0
#define SWI_NUM_FindMSB			        0
#define SWI_NUM_FindMsgPort			    0
#define SWI_NUM_FindNamedItem			0
#define SWI_NUM_FindNamedNode			0
#define SWI_NUM_FindNodeFromHead		0
#define SWI_NUM_FindNodeFromTail		0
#define SWI_NUM_FindSemaphore			0
#define SWI_NUM_FindTagArg			    0
#define SWI_NUM_FindTask			    0
#define SWI_NUM_FindVersionedItem		0
#define SWI_NUM_FirstNode			    0
#define SWI_NUM_free			        0
#define SWI_NUM_FreeMem			        0
#define SWI_NUM_FreeMemList			    0
#define SWI_NUM_FreeMemToMemList		0
#define SWI_NUM_FreeMemToMemLists		0
#define SWI_NUM_GetBankBits			    0
#define SWI_NUM_GetCurrentSignals		0
#define SWI_NUM_GetFolioFunc			0
#define SWI_NUM_GetMemAllocAlignment	0
#define SWI_NUM_GetMemTrackSize			0
#define SWI_NUM_GetMemType			    0
#define SWI_NUM_GetNodeCount			0
#define SWI_NUM_GetNodePosFromHead		0
#define SWI_NUM_GetNodePosFromTail		0
#define SWI_NUM_GetPageSize			    0
#define SWI_NUM_GetSysErr			    0
#define SWI_NUM_GetTagArg			    0
#define SWI_NUM_GetTaskSignals			0
#define SWI_NUM_InitList			    0
#define SWI_NUM_InsertNodeAfter			0
#define SWI_NUM_InsertNodeBefore		0
#define SWI_NUM_InsertNodeFromHead		0
#define SWI_NUM_InsertNodeFromTail		0
#define SWI_NUM_IsEmptyList			    0
#define SWI_NUM_IsItemOpened			0
#define SWI_NUM_IsListEmpty			    0
#define SWI_NUM_IsMemReadable			0
#define SWI_NUM_IsMemWritable			0
#define SWI_NUM_IsNode			        0
#define SWI_NUM_IsNodeB			        0
#define SWI_NUM_LastNode			    0
#define SWI_NUM_LockSemaphore			0
#define SWI_NUM_LookupItem			    0
#define SWI_NUM_malloc			        0
#define SWI_NUM_MkNodeID			    0
#define SWI_NUM_NextNode			    0
#define SWI_NUM_NextTagArg			    0
#define SWI_NUM_OpenNamedDevice			0
#define SWI_NUM_PrevNode			    0
#define SWI_NUM_PrintError			    0
#define SWI_NUM_PrintfSysErr			0
#define SWI_NUM_RemHead			        0
#define SWI_NUM_RemNode			        0
#define SWI_NUM_RemTail			        0
#define SWI_NUM_ReplySmallMsg			0
#define SWI_NUM_SampleSystemTimeTV		0
#define SWI_NUM_SanityCheckMemDebug		0
#define SWI_NUM_SendSmallMsg			0
#define SWI_NUM_SetNodePri			    0
#define SWI_NUM_UniversalInsertNode		0
#define SWI_NUM_UnlockSemaphore			0

#endif // _INC_SWI_NUM_STUBS_MEM